### ISSUE TITLE
Spotify auth token

### ISSUE THREAD

**Issue by ansarkhan** [enfenry/spotify_app#3]
Call to get Spotify token, we can save it in local storage for now

**Comment by enfenry** [comment]
https://github.com/spotify/web-api-auth-examples

Great resource for the 3 different options. Although, I was only able to get the authorization code workflow to work. Not sure which option we will ultimately want to use.

**Comment by enfenry** [comment]
UPDATE: only implicit grant flow will work. Has been implemented
